export interface iBook {
  book_id: string,
  name: string,
  language: string,
  category: string,
  alias: string,
  image: string,
  type: string,
  file: string,
  file_type: string,
  description: string,
  price: string,
  offer_price: string,
  total_pages: string,
  author: string,
  status: string,
  created_date: string,
  image_url: string,
  file_url: string,
  download_url: string,
  price_formatted: string,
  offer_price_formatted: string
}
